# Generated by Django 5.2.5 on 2025-10-27 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('instance_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Instância')),
                ('status', models.CharField(choices=[('connecting', 'Conectando'), ('open', 'Conectado'), ('close', 'Desconectado'), ('error', 'Erro')], default='connecting', max_length=20, verbose_name='Status')),
                ('qr_code_url', models.URLField(blank=True, null=True, verbose_name='URL do QR Code')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Telefone')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Instância WhatsApp',
                'verbose_name_plural': 'Instâncias WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='Olá! Bem-vindo ao nosso atendimento imobiliário. Como posso ajudá-lo?', verbose_name='Mensagem de Boas-vindas')),
                ('auto_response_enabled', models.BooleanField(default=True, verbose_name='Resposta Automática Ativa')),
                ('business_hours_start', models.TimeField(default='08:00', verbose_name='Horário de Início')),
                ('business_hours_end', models.TimeField(default='18:00', verbose_name='Horário de Fim')),
                ('weekend_enabled', models.BooleanField(default=False, verbose_name='Atendimento nos Fins de Semana')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_webhook.whatsappinstance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Bot WhatsApp',
                'verbose_name_plural': 'Bots WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Mensagem')),
                ('from_number', models.CharField(max_length=20, verbose_name='Número de Origem')),
                ('to_number', models.CharField(max_length=20, verbose_name='Número de Destino')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo')], default='text', max_length=20, verbose_name='Tipo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('direction', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Enviada')], max_length=20, verbose_name='Direção')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora')),
                ('processed', models.BooleanField(default=False, verbose_name='Processada')),
                ('response_sent', models.BooleanField(default=False, verbose_name='Resposta Enviada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_webhook.whatsappinstance', verbose_name='Instância')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-timestamp'],
            },
        ),
    ]
