# Generated by Django 5.2.5 on 2025-09-03 13:17

import django.db.models.deletion
import security.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Dataset')),
                ('tipo', models.CharField(choices=[('financeiro', 'Dados Financeiros'), ('imoveis', 'Dados de Imóveis'), ('contratos', 'Dados de Contratos'), ('manutencao', 'Dados de Manutenção'), ('inquilinos', 'Dados de Inquilinos'), ('proprietarios', 'Dados de Proprietários'), ('dashboard', 'Dashboard Geral')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('endpoint', models.CharField(max_length=200, verbose_name='Endpoint da API')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requer_autenticacao', models.BooleanField(default=True, verbose_name='Requer Autenticação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dataset Power BI',
                'verbose_name_plural': 'Datasets Power BI',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Configuração')),
                ('tenant_id', security.fields.EncryptedTextField(verbose_name='Tenant ID')),
                ('client_id', security.fields.EncryptedTextField(verbose_name='Client ID')),
                ('client_secret', security.fields.EncryptedTextField(verbose_name='Client Secret')),
                ('workspace_id', security.fields.EncryptedTextField(blank=True, null=True, verbose_name='Workspace ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração Power BI',
                'verbose_name_plural': 'Configurações Power BI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('metodo', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('status_code', models.IntegerField(verbose_name='Código de Status')),
                ('tempo_resposta', models.FloatField(verbose_name='Tempo de Resposta (ms)')),
                ('registros_retornados', models.IntegerField(default=0, verbose_name='Registros Retornados')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data do Acesso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerbi.powerbidataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Log de Acesso Power BI',
                'verbose_name_plural': 'Logs de Acesso Power BI',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.CreateModel(
            name='PowerBIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', security.fields.EncryptedTextField(verbose_name='Token de Acesso')),
                ('refresh_token', security.fields.EncryptedTextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerbi.powerbiconfig', verbose_name='Configuração')),
            ],
            options={
                'verbose_name': 'Token Power BI',
                'verbose_name_plural': 'Tokens Power BI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
