# Generated by Django 5.2.5 on 2025-09-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerbi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerbidataset',
            name='tipo',
            field=models.CharField(choices=[('financeiro', 'Dados Financeiros'), ('imoveis', 'Dados de Imóveis'), ('contratos', 'Dados de Contratos'), ('manutencao', 'Dados de Manutenção'), ('inquilinos', 'Dados de Inquilinos'), ('proprietarios', 'Dados de Proprietários'), ('bancas', 'Dados de Bancas de Feira'), ('dashboard', 'Dashboard Geral')], max_length=20, verbose_name='Tipo'),
        ),
    ]
