# Generated by Django 5.2.5 on 2025-09-05 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('profissional', 'Profissional'), ('empresarial', 'Empresarial'), ('personalizado', 'Personalizado')], max_length=20)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_usuarios', models.IntegerField(default=1)),
                ('max_imoveis', models.IntegerField(default=100)),
                ('max_contratos', models.IntegerField(default=50)),
                ('storage_gb', models.IntegerField(default=5)),
                ('api_calls_mes', models.IntegerField(default=1000)),
                ('suporte_prioritario', models.BooleanField(default=False)),
                ('backup_automatico', models.BooleanField(default=False)),
                ('subdominio_personalizado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano Comercial',
                'verbose_name_plural': 'Planos Comerciais',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subdominio', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('trial', 'Trial')], default='trial', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('trial_ate', models.DateTimeField(blank=True, null=True)),
                ('configuracoes', models.JSONField(blank=True, default=dict)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas.planocomercial')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='saas.tenant')),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('cor_primaria', models.CharField(default='#007bff', max_length=7)),
                ('cor_secundaria', models.CharField(default='#6c757d', max_length=7)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('configuracoes_email', models.JSONField(blank=True, default=dict)),
                ('configuracoes_api', models.JSONField(blank=True, default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='saas.tenant')),
            ],
            options={
                'verbose_name': 'Configuração do Tenant',
                'verbose_name_plural': 'Configurações dos Tenants',
            },
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('usuarios_ativos', models.IntegerField(default=0)),
                ('imoveis_cadastrados', models.IntegerField(default=0)),
                ('contratos_ativos', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('storage_usado_mb', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_uso', to='saas.tenant')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'unique_together': {('tenant', 'data')},
            },
        ),
    ]
