# Generated by Django 5.2.5 on 2025-09-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocomercial',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Plano de trial gratuito'),
        ),
        migrations.AlterField(
            model_name='planocomercial',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planocomercial',
            name='tipo',
            field=models.CharField(choices=[('trial', 'Trial Gratuito'), ('basico', 'Básico'), ('profissional', 'Profissional'), ('empresarial', 'Empresarial'), ('personalizado', 'Personalizado')], max_length=20),
        ),
    ]
