# Generated by Django 5.2.5 on 2025-09-09 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_planocomercial_is_trial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPlano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_pagamento', models.CharField(editable=False, max_length=64, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('nome_pagador', models.CharField(max_length=200)),
                ('email_pagador', models.EmailField(max_length=254)),
                ('telefone_pagador', models.CharField(blank=True, max_length=20)),
                ('documento_pagador', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.planocomercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento de Plano',
                'verbose_name_plural': 'Pagamentos de Planos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
