# Generated by Django 5.2.5 on 2025-09-11 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_pagamentoplano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_verificacao', models.DateTimeField(blank=True, null=True)),
                ('tentativas_envio', models.IntegerField(default=0)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacao_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificação de Email',
                'verbose_name_plural': 'Verificações de Email',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
