# Generated by Django 5.2.5 on 2025-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_verificacaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado'), ('trial', 'Trial'), ('pendente_pagamento', 'Pendente Pagamento')], default='trial', max_length=20),
        ),
    ]
