# Generated by Django 5.2.5 on 2025-09-03 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0005_alter_notafiscal_chave_acesso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_habilitado', models.BooleanField(default=True)),
                ('pix_chave', models.CharField(blank=True, max_length=200)),
                ('pix_nome_recebedor', models.CharField(blank=True, max_length=200)),
                ('cartao_habilitado', models.BooleanField(default=False)),
                ('gateway_api_key', models.CharField(blank=True, max_length=500)),
                ('gateway_secret_key', models.CharField(blank=True, max_length=500)),
                ('gateway_endpoint', models.URLField(blank=True)),
                ('boleto_habilitado', models.BooleanField(default=False)),
                ('banco_codigo', models.CharField(blank=True, max_length=10)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('conta', models.CharField(blank=True, max_length=20)),
                ('tempo_expiracao_horas', models.IntegerField(default=24)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('taxa_processamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('url_sucesso', models.URLField(blank=True)),
                ('url_erro', models.URLField(blank=True)),
                ('url_cancelamento', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='PagamentoOnline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_pagamento', models.CharField(editable=False, max_length=64, unique=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto Bancário'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('nome_pagador', models.CharField(blank=True, max_length=200)),
                ('email_pagador', models.EmailField(blank=True, max_length=254)),
                ('telefone_pagador', models.CharField(blank=True, max_length=20)),
                ('tentativas_processamento', models.IntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_online', to='financeiro.parcela')),
            ],
            options={
                'verbose_name': 'Pagamento Online',
                'verbose_name_plural': 'Pagamentos Online',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('TENTATIVA', 'Tentativa de Pagamento'), ('APROVACAO', 'Aprovação'), ('REJEICAO', 'Rejeição'), ('CANCELAMENTO', 'Cancelamento'), ('EXPIRACAO', 'Expiração'), ('ERRO', 'Erro')], max_length=20)),
                ('descricao', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pagamentos.pagamentoonline')),
            ],
            options={
                'verbose_name': 'Log de Pagamento',
                'verbose_name_plural': 'Logs de Pagamento',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamentoonline',
            index=models.Index(fields=['token_pagamento'], name='pagamentos__token_p_ecaab9_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoonline',
            index=models.Index(fields=['status'], name='pagamentos__status_4cddbb_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentoonline',
            index=models.Index(fields=['data_criacao'], name='pagamentos__data_cr_199b63_idx'),
        ),
    ]
