# Generated by Django 5.2.5 on 2025-10-06 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0018_alter_imovel_inscricao_municipal_and_more'),
        ('pagamentos', '0003_pagamentoonline_categoria_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoBancaFeira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_pagamento', models.CharField(editable=False, max_length=64, unique=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto Bancário'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('tipo_vencimento', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMANAL', 'Semanal')], default='MENSAL', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('nome_pagador', models.CharField(blank=True, max_length=200)),
                ('email_pagador', models.EmailField(blank=True, max_length=254)),
                ('telefone_pagador', models.CharField(blank=True, max_length=20)),
                ('tentativas_processamento', models.IntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato_banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='imoveis.contratobancafeira')),
            ],
            options={
                'verbose_name': 'Pagamento de Banca da Feira',
                'verbose_name_plural': 'Pagamentos de Bancas da Feira',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogPagamentoBanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('TENTATIVA', 'Tentativa de Pagamento'), ('APROVACAO', 'Aprovação'), ('REJEICAO', 'Rejeição'), ('CANCELAMENTO', 'Cancelamento'), ('EXPIRACAO', 'Expiração'), ('ATUALIZACAO_CONTRATO', 'Atualização de Contrato'), ('ERRO', 'Erro')], max_length=30)),
                ('descricao', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pagamento_banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pagamentos.pagamentobancafeira')),
            ],
            options={
                'verbose_name': 'Log de Pagamento de Banca',
                'verbose_name_plural': 'Logs de Pagamentos de Bancas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamentobancafeira',
            index=models.Index(fields=['token_pagamento'], name='pagamentos__token_p_6f9fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentobancafeira',
            index=models.Index(fields=['status'], name='pagamentos__status_7293a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentobancafeira',
            index=models.Index(fields=['data_criacao'], name='pagamentos__data_cr_8b27b7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamentobancafeira',
            index=models.Index(fields=['data_vencimento'], name='pagamentos__data_ve_699312_idx'),
        ),
    ]
