# Generated by Django 5.2.5 on 2025-09-02 20:55

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='pix',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='agencia',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='banco',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conta',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pix',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=security.fields.CPFCNPJField(max_length=510, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg_ie',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
    ]
