# Generated by Django 5.1.5 on 2025-09-22 17:15

import django.db.models.deletion
import security.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pessoa_agencia_alter_pessoa_banco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Perfil')),
                ('tipo', models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('corretor', 'Corretor'), ('financeiro', 'Financeiro'), ('atendimento', 'Atendimento'), ('consulta', 'Consulta')], max_length=20, verbose_name='Tipo de Perfil')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='agencia',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='banco',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conta',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pix',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg_ie',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
        migrations.CreateModel(
            name='LogAlteracaoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('exclusao', 'Exclusão'), ('ativacao', 'Ativação'), ('desativacao', 'Desativação'), ('atribuicao', 'Atribuição de Perfil'), ('remocao', 'Remoção de Perfil')], max_length=20, verbose_name='Ação')),
                ('perfil_anterior', models.CharField(blank=True, max_length=100, verbose_name='Perfil Anterior')),
                ('perfil_novo', models.CharField(blank=True, max_length=100, verbose_name='Perfil Novo')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('usuario_alterado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_perfil_alterado', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_perfil_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Alteração de Perfil',
                'verbose_name_plural': 'Logs de Alterações de Perfil',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfilusuario', verbose_name='Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário com Perfil',
                'verbose_name_plural': 'Usuários com Perfil',
            },
        ),
        migrations.CreateModel(
            name='AbrangenciaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('imoveis', 'Imóveis'), ('contratos', 'Contratos'), ('financeiro', 'Financeiro'), ('pessoas', 'Pessoas'), ('manutencao', 'Manutenção'), ('documentos', 'Documentos'), ('notificacoes', 'Notificações'), ('relatorios', 'Relatórios'), ('configuracoes', 'Configurações'), ('bancas', 'Bancas de Feira')], max_length=20, verbose_name='Módulo')),
                ('acao', models.CharField(choices=[('visualizar', 'Visualizar'), ('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('aprovar', 'Aprovar'), ('exportar', 'Exportar')], max_length=20, verbose_name='Ação')),
                ('permitido', models.BooleanField(default=True, verbose_name='Permitido')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abrangencias', to='core.perfilusuario')),
            ],
            options={
                'verbose_name': 'Abrangência de Perfil',
                'verbose_name_plural': 'Abrangências de Perfil',
                'unique_together': {('perfil', 'modulo', 'acao')},
            },
        ),
    ]
