# Generated by Django 5.1.5 on 2025-08-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('PERIODICA', 'Periódica')], max_length=20)),
                ('data_agendamento', models.DateTimeField()),
                ('data_realizacao', models.DateTimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('assinatura_digital', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-data_agendamento'],
            },
        ),
        migrations.CreateModel(
            name='ItemVistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vistorias/')),
                ('vistoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='documentos.vistoria')),
            ],
            options={
                'verbose_name': 'Item de Vistoria',
                'verbose_name_plural': 'Itens de Vistoria',
            },
        ),
    ]
