# Generated by Django 5.2.5 on 2025-09-05 19:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_dias', models.IntegerField(default=7, verbose_name='Dias de Trial Gratuito')),
                ('permitir_trial', models.BooleanField(default=True, verbose_name='Permitir Trial')),
                ('bloquear_acesso_vencido', models.BooleanField(default=True, verbose_name='Bloquear Acesso Vencido')),
                ('dias_graca', models.IntegerField(default=3, verbose_name='Dias de Graça após Vencimento')),
                ('email_cobranca', models.EmailField(max_length=254, verbose_name='Email para Cobrança')),
                ('mensagem_bloqueio', models.TextField(default='Sua assinatura expirou. Renove para continuar usando o sistema.', verbose_name='Mensagem de Bloqueio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('VITALICIO', 'Vitalício'), ('TRIAL', 'Trial Gratuito')], max_length=20, verbose_name='Tipo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('duracao_dias', models.IntegerField(help_text='0 para vitalício', verbose_name='Duração em Dias')),
                ('max_imoveis', models.IntegerField(default=0, help_text='0 para ilimitado', verbose_name='Máximo de Imóveis')),
                ('max_contratos', models.IntegerField(default=0, help_text='0 para ilimitado', verbose_name='Máximo de Contratos')),
                ('max_usuarios', models.IntegerField(default=1, verbose_name='Máximo de Usuários')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['preco'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('SUSPENSA', 'Suspensa'), ('TRIAL', 'Trial')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('renovacao_automatica', models.BooleanField(default=True, verbose_name='Renovação Automática')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assinaturas.planoassinatura', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura do Usuário',
                'verbose_name_plural': 'Assinaturas dos Usuários',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('forma_pagamento', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, verbose_name='Referência Externa')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='assinaturas.assinaturausuario')),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Histórico de Pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
