# Generated by Django 5.1.5 on 2025-08-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_condominio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_iptu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_outros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('boleto_gerado', models.BooleanField(default=False)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento'],
                'unique_together': {('contrato', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('serie', models.CharField(default='001', max_length=10)),
                ('data_emissao', models.DateField()),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao_servico', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EMITIDA', 'Emitida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('chave_acesso', models.CharField(blank=True, max_length=100)),
                ('xml_nfe', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.parcela')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_repasse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_honorario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_repasse', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('comprovante', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.parcela')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
            options={
                'verbose_name': 'Repasse',
                'verbose_name_plural': 'Repasses',
                'ordering': ['-data_repasse'],
            },
        ),
    ]
