# Generated by Django 5.2.5 on 2025-09-05 16:36

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_notafiscal_chave_acesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='tipo',
            field=models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('CONDOMINIO', 'Condomínio'), ('IPTU', 'IPTU'), ('SEGURO', 'Seguro'), ('OUTROS', 'Outros')], default='ALUGUEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
    ]
