# Generated by Django 5.2.5 on 2025-10-03 17:25

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_remove_polo_moda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
    ]
