# Generated by Django 5.2.5 on 2025-12-08 16:19

import django.db.models.deletion
import django.utils.timezone
import security.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_alter_notafiscal_chave_acesso_and_more'),
        ('imoveis', '0021_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0007_evolutioninstance_evolutionmessage_evolutionwebhook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
        migrations.CreateModel(
            name='CaixaSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('CONFERIDA', 'Conferida')], default='ABERTA', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('aberto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('banca_feira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to='imoveis.bancafeira')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-data', '-hora_abertura'],
            },
        ),
        migrations.CreateModel(
            name='CaixaMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('TRANSFERENCIA', 'Transferência')], default='DINHEIRO', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('banca_feira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to='imoveis.bancafeira')),
                ('contrato_banca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.contratobancafeira')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.caixasessao')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='caixasessao',
            index=models.Index(fields=['tenant', 'data'], name='financeiro__tenant__2ebb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='caixasessao',
            index=models.Index(fields=['tenant', 'banca_feira', 'status'], name='financeiro__tenant__6088b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caixasessao',
            unique_together={('tenant', 'banca_feira', 'data')},
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['tenant', 'sessao'], name='financeiro__tenant__5eca28_idx'),
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['tenant', 'banca_feira'], name='financeiro__tenant__68af32_idx'),
        ),
        migrations.AddIndex(
            model_name='caixamovimento',
            index=models.Index(fields=['tenant', 'tipo'], name='financeiro__tenant__029a67_idx'),
        ),
    ]
