# Generated by Django 4.2.30 on 2026-05-04 13:41

from django.db import migrations
import security.fields


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_alter_caixamovimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
        migrations.DeleteModel(
            name='CaixaMovimento',
        ),
        migrations.DeleteModel(
            name='CaixaSessao',
        ),
    ]
