# Generated by Django 5.2.5 on 2025-09-10 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAssinatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_pagamento', models.CharField(editable=False, max_length=64, unique=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO', 'Boleto Bancário'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20, verbose_name='Método de Pagamento')),
                ('tipo_pagamento', models.CharField(choices=[('ASSINATURA_NOVA', 'Nova Assinatura'), ('RENOVACAO', 'Renovação'), ('UPGRADE', 'Upgrade de Plano'), ('DOWNGRADE', 'Downgrade de Plano')], default='ASSINATURA_NOVA', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Transação')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Resposta do Gateway')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('nome_pagador', models.CharField(blank=True, max_length=200, verbose_name='Nome do Pagador')),
                ('email_pagador', models.EmailField(blank=True, max_length=254, verbose_name='Email do Pagador')),
                ('telefone_pagador', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Pagador')),
                ('tentativas_processamento', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último Erro')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('periodo_inicio', models.DateTimeField(verbose_name='Início do Período')),
                ('periodo_fim', models.DateTimeField(verbose_name='Fim do Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_assinatura', to='assinaturas.assinaturausuario')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assinaturas.planoassinatura', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Pagamento de Assinatura',
                'verbose_name_plural': 'Pagamentos de Assinatura',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_pagamento'], name='assinaturas_token_p_f64d4a_idx'), models.Index(fields=['status'], name='assinaturas_status_4b8019_idx'), models.Index(fields=['data_criacao'], name='assinaturas_data_cr_5ef628_idx'), models.Index(fields=['assinatura'], name='assinaturas_assinat_4c5ed1_idx')],
            },
        ),
    ]
