# Generated by Django 5.2.5 on 2025-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_pagamentoassinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturausuario',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
    ]
