# Generated by Django 5.2.5 on 2025-09-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('permanent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IP Bloqueado',
                'verbose_name_plural': 'IPs Bloqueados',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=150)),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_fingerprint', models.CharField(max_length=255, unique=True)),
                ('authorized_ips', models.JSONField(default=list, help_text='Lista de IPs autorizados')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32)),
                ('backup_codes', models.JSONField(default=list)),
                ('last_security_check', models.DateTimeField(auto_now=True)),
                ('security_level', models.CharField(choices=[('BASIC', 'Básico'), ('ENHANCED', 'Aprimorado'), ('MAXIMUM', 'Máximo')], default='ENHANCED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário Master',
                'verbose_name_plural': 'Usuários Master',
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Bem-sucedido'), ('LOGIN_FAILED', 'Tentativa de Login Falhada'), ('UNAUTHORIZED_ACCESS', 'Acesso Não Autorizado'), ('IP_BLOCKED', 'IP Bloqueado'), ('HARDWARE_MISMATCH', 'Hardware Não Reconhecido'), ('ADMIN_ACTION', 'Ação Administrativa'), ('DATA_EXPORT', 'Exportação de Dados'), ('SYSTEM_CHANGE', 'Alteração no Sistema'), ('SECURITY_BREACH', 'Violação de Segurança')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'ordering': ['-timestamp'],
            },
        ),
    ]
