# Generated by Django 5.2.5 on 2025-09-02 20:55

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_masteruser_backup_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='backup_codes',
            field=security.fields.EncryptedJSONField(blank=True, default=list, help_text='Códigos de backup para 2FA'),
        ),
        migrations.AlterField(
            model_name='masteruser',
            name='two_factor_secret',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=security.fields.EncryptedCharField(max_length=4000),
        ),
    ]
