# Generated by Django 5.2.5 on 2025-10-06 17:37

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_alter_masteruser_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='two_factor_secret',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=security.fields.EncryptedCharField(max_length=4000),
        ),
    ]
