# Generated by Django 4.2.30 on 2026-05-04 13:56

from django.db import migrations
import security.fields


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_alter_masteruser_two_factor_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='two_factor_secret',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=security.fields.EncryptedCharField(max_length=4000),
        ),
    ]
