# Generated by Django 5.2.5 on 2025-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_securitylog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruser',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Códigos de backup para 2FA'),
        ),
    ]
