# Generated by Django 5.2.5 on 2025-10-06 17:37

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pessoa_agencia_alter_pessoa_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='agencia',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='banco',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conta',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pix',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg_ie',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
    ]
