# Generated by Django 4.2.30 on 2026-05-04 13:56

from django.db import migrations
import security.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_documento_banca_remove_ticket_banca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='agencia',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='banco',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='conta',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pix',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg_ie',
            field=security.fields.EncryptedCharField(blank=True, max_length=510),
        ),
    ]
