# Generated by Django 5.1.5 on 2025-08-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoimovel',
            options={'ordering': ['-principal', '-created_at'], 'verbose_name': 'Foto do Imóvel', 'verbose_name_plural': 'Fotos dos Imóveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADO', 'Ocupado'), ('MANUTENCAO', 'Em Manutenção'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Seguro'),
        ),
        migrations.AlterField(
            model_name='fotoimovel',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fotoimovel',
            name='foto',
            field=models.ImageField(upload_to='imoveis/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='fotoimovel',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área Construída (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área Total (m²)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='banheiros',
            field=models.IntegerField(default=0, verbose_name='Banheiros'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível para Locação'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('MISTO', 'Misto')], max_length=20, verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='mobiliado',
            field=models.BooleanField(default=False, verbose_name='Mobiliado'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(default=0, verbose_name='Quartos'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('COMERCIAL', 'Comercial'), ('TERRENO', 'Terreno'), ('CHACARA', 'Chácara'), ('KITNET', 'Kitnet'), ('SOBRADO', 'Sobrado')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_garagem',
            field=models.IntegerField(default=0, verbose_name='Vagas de Garagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aluguel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_condominio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Condomínio'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_iptu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do IPTU'),
        ),
    ]
