# Generated by Django 5.2.5 on 2025-09-08 17:22

import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0002_planocomercial_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
