# Generated by Django 5.2.5 on 2025-09-09 16:42

import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pessoa_agencia_alter_pessoa_banco_and_more'),
        ('imoveis', '0005_imovel_tenant_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0003_pagamentoplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.CreateModel(
            name='BancaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da Banca')),
                ('tipo', models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('VESTUARIO', 'Vestuário'), ('CALCADOS', 'Calçados'), ('ACESSORIOS', 'Acessórios'), ('ARTESANATO', 'Artesanato'), ('FLORES', 'Flores e Plantas'), ('FRUTAS', 'Frutas e Verduras'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Comércio')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor da Feira')),
                ('numero_banca', models.CharField(max_length=10, verbose_name='Número da Banca')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização/Referência')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Área Total (m²)')),
                ('tem_energia', models.BooleanField(default=True, verbose_name='Possui Energia Elétrica')),
                ('tem_agua', models.BooleanField(default=False, verbose_name='Possui Água')),
                ('cobertura', models.BooleanField(default=True, verbose_name='Possui Cobertura')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Aluguel')),
                ('valor_taxa_feira', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taxa da Feira')),
                ('valor_limpeza', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taxa de Limpeza')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('equipamentos', models.TextField(blank=True, verbose_name='Equipamentos Inclusos')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada'), ('MANUTENCAO', 'Em Manutenção'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20, verbose_name='Status')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Locação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario', verbose_name='Proprietário')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Banca de Feira',
                'verbose_name_plural': 'Bancas de Feira',
                'ordering': ['setor', 'numero_banca'],
            },
        ),
        migrations.CreateModel(
            name='FotoBancaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='bancas/fotos/', verbose_name='Foto')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('principal', models.BooleanField(default=False, verbose_name='Foto Principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.bancafeira')),
            ],
            options={
                'verbose_name': 'Foto da Banca',
                'verbose_name_plural': 'Fotos das Bancas',
                'ordering': ['-principal', '-created_at'],
            },
        ),
    ]
