# Generated by Django 5.2.5 on 2025-09-09 17:20

import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pessoa_agencia_alter_pessoa_banco_and_more'),
        ('imoveis', '0006_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0003_pagamentoplano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.CreateModel(
            name='ContratoBancaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Aluguel')),
                ('valor_taxa_feira', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa da Feira')),
                ('valor_limpeza', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Limpeza')),
                ('valor_seguranca', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Segurança')),
                ('dia_vencimento', models.IntegerField(default=10, verbose_name='Dia de Vencimento')),
                ('tipo_reajuste', models.CharField(choices=[('IGP-M', 'IGP-M'), ('IPCA', 'IPCA'), ('INPC', 'INPC'), ('FIXO', 'Percentual Fixo')], max_length=10, verbose_name='Tipo de Reajuste')),
                ('percentual_reajuste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Reajuste')),
                ('periodicidade_reajuste', models.IntegerField(default=12, verbose_name='Periodicidade do Reajuste (meses)')),
                ('caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caução')),
                ('fiador', models.CharField(blank=True, max_length=200, verbose_name='Fiador')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('clausulas_especiais', models.TextField(blank=True, verbose_name='Cláusulas Especiais')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('RESCINDIDO', 'Rescindido'), ('RENOVADO', 'Renovado')], default='ATIVO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('banca_feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.bancafeira', verbose_name='Banca de Feira')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inquilino', verbose_name='Locatário')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Contrato de Banca de Feira',
                'verbose_name_plural': 'Contratos de Bancas de Feira',
                'ordering': ['-created_at'],
            },
        ),
    ]
