# Generated by Django 5.1.5 on 2025-09-25 20:26

import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0006_pagamentoplano_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancafeira',
            name='altura_bancas',
            field=models.IntegerField(default=1, verbose_name='Altura (bancas)'),
        ),
        migrations.AddField(
            model_name='bancafeira',
            name='largura_bancas',
            field=models.IntegerField(default=1, verbose_name='Largura (bancas)'),
        ),
        migrations.AddField(
            model_name='bancafeira',
            name='posicao_coluna',
            field=models.IntegerField(default=1, verbose_name='Coluna no Mapa'),
        ),
        migrations.AddField(
            model_name='bancafeira',
            name='posicao_linha',
            field=models.IntegerField(default=1, verbose_name='Linha no Mapa'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.CreateModel(
            name='LayoutFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Layout')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor da Feira')),
                ('linhas', models.IntegerField(default=10, verbose_name='Número de Linhas')),
                ('colunas', models.IntegerField(default=15, verbose_name='Número de Colunas')),
                ('cor_fundo', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Cor de Fundo')),
                ('cor_grade', models.CharField(default='#dee2e6', max_length=7, verbose_name='Cor da Grade')),
                ('areas_especiais', models.JSONField(blank=True, default=dict, verbose_name='Áreas Especiais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Layout Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Layout da Feira',
                'verbose_name_plural': 'Layouts da Feira',
                'ordering': ['setor', 'nome'],
            },
        ),
    ]
