# Generated by Django 5.2.5 on 2025-10-02 14:35

import django.core.validators
import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0006_pagamentoplano_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.CreateModel(
            name='TemplateMapaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('categoria', models.CharField(choices=[('TRADICIONAL', 'Feira Tradicional'), ('COBERTA', 'Feira Coberta'), ('SHOPPING_POPULAR', 'Shopping Popular'), ('POLO_MODA', 'Polo da Moda'), ('ALIMENTACAO', 'Praça de Alimentação'), ('ARTESANATO', 'Feira de Artesanato'), ('PERSONALIZADO', 'Personalizado')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('configuracao_base', models.JSONField(verbose_name='Configuração Base')),
                ('preview_imagem', models.TextField(blank=True, verbose_name='Preview do Template')),
                ('publico', models.BooleanField(default=False, verbose_name='Template Público')),
                ('ativo', models.BooleanField(default=True, verbose_name='Template Ativo')),
                ('vezes_usado', models.IntegerField(default=0, verbose_name='Vezes Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Template de Mapa',
                'verbose_name_plural': 'Templates de Mapas',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMapaFeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor da Feira')),
                ('largura_mapa', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Largura do Mapa (colunas)')),
                ('altura_mapa', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)], verbose_name='Altura do Mapa (linhas)')),
                ('cor_fundo_mapa', models.CharField(default='#f8f9fa', max_length=7, verbose_name='Cor de Fundo do Mapa')),
                ('cor_grade', models.CharField(default='#dee2e6', max_length=7, verbose_name='Cor da Grade')),
                ('mostrar_grade', models.BooleanField(default=True, verbose_name='Mostrar Grade')),
                ('largura_banca_padrao', models.IntegerField(default=35, verbose_name='Largura Padrão da Banca (px)')),
                ('altura_banca_padrao', models.IntegerField(default=25, verbose_name='Altura Padrão da Banca (px)')),
                ('espacamento_bancas', models.IntegerField(default=3, verbose_name='Espaçamento entre Bancas (px)')),
                ('cores_por_tipo', models.JSONField(default=dict, help_text='JSON com cores para cada tipo de elemento', verbose_name='Cores por Tipo de Elemento')),
                ('layout_elementos', models.JSONField(default=list, help_text='Matriz com a configuração de cada posição do mapa', verbose_name='Layout dos Elementos')),
                ('responsivo', models.BooleanField(default=True, verbose_name='Layout Responsivo')),
                ('largura_minima_mobile', models.IntegerField(default=25, verbose_name='Largura Mínima Mobile (px)')),
                ('altura_minima_mobile', models.IntegerField(default=20, verbose_name='Altura Mínima Mobile (px)')),
                ('permitir_clique_bancas', models.BooleanField(default=True, verbose_name='Permitir Clique nas Bancas')),
                ('mostrar_tooltip', models.BooleanField(default=True, verbose_name='Mostrar Tooltip ao Passar Mouse')),
                ('animacao_hover', models.BooleanField(default=True, verbose_name='Animação no Hover')),
                ('mostrar_legenda', models.BooleanField(default=True, verbose_name='Mostrar Legenda')),
                ('posicao_legenda', models.CharField(choices=[('bottom', 'Embaixo'), ('right', 'Direita'), ('top', 'Em Cima'), ('left', 'Esquerda')], default='bottom', max_length=20, verbose_name='Posição da Legenda')),
                ('mostrar_estatisticas', models.BooleanField(default=True, verbose_name='Mostrar Estatísticas')),
                ('estatisticas_personalizadas', models.JSONField(default=list, help_text='Lista de estatísticas customizadas para exibir', verbose_name='Estatísticas Personalizadas')),
                ('permitir_exportar_pdf', models.BooleanField(default=True, verbose_name='Permitir Exportar PDF')),
                ('permitir_exportar_imagem', models.BooleanField(default=True, verbose_name='Permitir Exportar Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Configuração Ativa')),
                ('padrao', models.BooleanField(default=False, verbose_name='Configuração Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuração de Mapa',
                'verbose_name_plural': 'Configurações de Mapas',
                'ordering': ['-padrao', 'setor', 'nome'],
                'unique_together': {('tenant', 'setor', 'padrao')},
            },
        ),
    ]
