# Generated by Django 5.2.5 on 2025-10-06 19:58

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0018_alter_imovel_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancafeira',
            name='status_pagamento',
            field=models.CharField(choices=[('EM_DIA', 'Em dia'), ('A_VENCER', 'A vencer'), ('VENCIDO', 'Vencido')], default='EM_DIA', max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='bancafeira',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada'), ('MANUTENCAO', 'Em Manutenção'), ('INDISPONIVEL', 'Indisponível'), ('JURIDICO', 'Jurídico'), ('VAZIA', 'Vazia')], default='DISPONIVEL', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
