# Generated by Django 5.2.5 on 2026-03-10 18:03

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0024_alter_configuracaomapafeira_altura_mapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
