# Generated by Django 5.2.5 on 2026-03-10 18:43

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0025_alter_imovel_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancafeira',
            name='posicao_coluna',
            field=models.IntegerField(default=0, verbose_name='Coluna no Mapa'),
        ),
        migrations.AlterField(
            model_name='bancafeira',
            name='posicao_linha',
            field=models.IntegerField(default=0, verbose_name='Linha no Mapa'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
