# Generated by Django 5.1.5 on 2025-08-20 18:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_condominio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_iptu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dia_vencimento', models.IntegerField(default=10)),
                ('tipo_reajuste', models.CharField(choices=[('IGP-M', 'IGP-M'), ('IPCA', 'IPCA'), ('INPC', 'INPC'), ('FIXO', 'Percentual Fixo')], max_length=10)),
                ('percentual_reajuste', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('periodicidade_reajuste', models.IntegerField(default=12)),
                ('percentual_honorario', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('caucao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('RESCINDIDO', 'Rescindido'), ('RENOVADO', 'Renovado')], default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.inquilino')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReajusteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reajuste', models.DateField()),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indice_aplicado', models.DecimalField(decimal_places=4, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reajustes', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Reajuste de Contrato',
                'verbose_name_plural': 'Reajustes de Contratos',
                'ordering': ['-data_reajuste'],
            },
        ),
    ]
