# Generated by Django 5.2.5 on 2025-09-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('saas', '0002_planocomercial_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant', verbose_name='Tenant'),
        ),
    ]
