# Generated by Django 5.2.5 on 2025-09-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoplano',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
    ]
