# Generated by Django 5.2.5 on 2025-10-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_pagamentoplano_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token de Acesso')),
                ('api_key', models.CharField(help_text='Chave de API global para administração', max_length=255, verbose_name='API Key Global')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('erro', 'Erro')], default='inativo', max_length=20, verbose_name='Status')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do WhatsApp')),
                ('server_url', models.URLField(default='http://localhost:8080', verbose_name='URL do Servidor')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Configurações Avançadas')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_instance', to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Instância Evolution API',
                'verbose_name_plural': 'Instâncias Evolution API',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Mensagem')),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], max_length=10, verbose_name='Direção')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('location', 'Localização'), ('contact', 'Contato')], max_length=20, verbose_name='Tipo de Mensagem')),
                ('from_number', models.CharField(max_length=20, verbose_name='Número Remetente')),
                ('to_number', models.CharField(max_length=20, verbose_name='Número Destinatário')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('timestamp', models.DateTimeField(verbose_name='Data/Hora')),
                ('raw_data', models.JSONField(verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='saas.evolutioninstance', verbose_name='Instância')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_messages', to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Mensagem Evolution API',
                'verbose_name_plural': 'Mensagens Evolution API',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('message', 'Mensagem'), ('status', 'Status'), ('connection', 'Conexão'), ('qrcode', 'QR Code'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Evento')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='URL do Webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.JSONField(verbose_name='Dados do Webhook')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='saas.evolutioninstance', verbose_name='Instância')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_webhooks', to='saas.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Webhook Evolution API',
                'verbose_name_plural': 'Webhooks Evolution API',
                'ordering': ['-created_at'],
            },
        ),
    ]
