# Generated by Django 5.2.5 on 2025-08-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_exercicio', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto_vista', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_vencimento_vista', models.DateField()),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('forma_pagamento', models.CharField(choices=[('VISTA', 'À Vista'), ('PARCELADO', 'Parcelado')], default='VISTA', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('PARCELADO', 'Parcelado'), ('ISENTO', 'Isento')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iptus', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'IPTU',
                'verbose_name_plural': 'IPTUs',
                'ordering': ['-ano_exercicio'],
                'unique_together': {('imovel', 'ano_exercicio')},
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguradora', models.CharField(max_length=100)),
                ('tipo_seguro', models.CharField(choices=[('INCENDIO', 'Seguro Incêndio'), ('RESIDENCIAL', 'Seguro Residencial'), ('COMERCIAL', 'Seguro Comercial'), ('VIDA', 'Seguro de Vida'), ('FIANCA', 'Seguro Fiança')], max_length=20)),
                ('numero_apolice', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSAL', max_length=20)),
                ('cobertura', models.TextField()),
                ('franquia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente Renovação')], default='ATIVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='contratos.contrato')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaIPTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iptu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_iptu', to='financeiro.iptu')),
            ],
            options={
                'verbose_name': 'Parcela IPTU',
                'verbose_name_plural': 'Parcelas IPTU',
                'ordering': ['numero_parcela'],
                'unique_together': {('iptu', 'numero_parcela')},
            },
        ),
        migrations.CreateModel(
            name='ParcelaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_seguro', to='financeiro.seguro')),
            ],
            options={
                'verbose_name': 'Parcela Seguro',
                'verbose_name_plural': 'Parcelas Seguro',
                'ordering': ['data_vencimento'],
                'unique_together': {('seguro', 'numero_parcela')},
            },
        ),
    ]
