# Generated by Django 5.2.5 on 2025-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_iptu_seguro_parcelaiptu_parcelaseguro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Nota Fiscal Eletrônica', 'verbose_name_plural': 'Notas Fiscais Eletrônicas'},
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('numero', 'serie')},
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='aliquota_iss',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Alíquota ISS (%)'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='nfe/pdf/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='arquivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='nfe/xml/', verbose_name='Arquivo XML'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='base_calculo_iss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base de Cálculo ISS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_documento',
            field=models.CharField(default=0.0, max_length=18, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_nome',
            field=models.CharField(default=0, max_length=200, verbose_name='Nome/Razão Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='cliente_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='parcelas',
            field=models.ManyToManyField(blank=True, to='financeiro.parcela', verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID no Provedor'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='provider_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Resposta do Provedor'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tentativas_envio',
            field=models.PositiveIntegerField(default=0, verbose_name='Tentativas de Envio'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='ultimo_erro',
            field=models.TextField(blank=True, null=True, verbose_name='Último Erro'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_servicos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor dos Serviços'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo XML'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='descricao_servico',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='serie',
            field=models.PositiveIntegerField(default=1, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_iss',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor ISS'),
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='valor_servico',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='xml_nfe',
        ),
    ]
