# Generated by Django 5.2.5 on 2025-09-02 20:55

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_notafiscal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente_documento',
            field=security.fields.CPFCNPJField(max_length=510, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
    ]
