# Generated by Django 5.1.5 on 2025-09-22 19:31

import django.db.models.deletion
import security.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_tenant'),
        ('financeiro', '0010_alter_notafiscal_chave_acesso_and_more'),
        ('imoveis', '0009_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0006_pagamentoplano_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('LIMPEZA', 'Limpeza'), ('SEGURANCA', 'Segurança'), ('ADMINISTRACAO', 'Administração'), ('MARKETING', 'Marketing'), ('JURIDICO', 'Jurídico'), ('CONTABILIDADE', 'Contabilidade'), ('IMPOSTOS', 'Impostos'), ('COMBUSTIVEL', 'Combustível'), ('ALIMENTACAO', 'Alimentação'), ('TRANSPORTE', 'Transporte'), ('MATERIAL_ESCRITORIO', 'Material de Escritório'), ('TELEFONE_INTERNET', 'Telefone/Internet'), ('ENERGIA_ELETRICA', 'Energia Elétrica'), ('AGUA_ESGOTO', 'Água/Esgoto'), ('SEGUROS', 'Seguros'), ('TAXAS_BANCARIAS', 'Taxas Bancárias'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor/Beneficiário')),
                ('numero_documento', models.CharField(blank=True, help_text='Número da nota fiscal, recibo, etc.', max_length=50, verbose_name='Número do Documento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato relacionado à despesa (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato', verbose_name='Contrato')),
                ('imovel', models.ForeignKey(blank=True, help_text='Imóvel relacionado à despesa (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel', verbose_name='Imóvel')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'ordering': ['-data_vencimento', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'data_vencimento'], name='financeiro__tenant__edc50d_idx'), models.Index(fields=['tenant', 'categoria'], name='financeiro__tenant__610c97_idx'), models.Index(fields=['tenant', 'status'], name='financeiro__tenant__b3766d_idx')],
            },
        ),
    ]
