# Generated by Django 5.2.5 on 2025-12-08 16:35

import django.db.models.deletion
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_alter_notafiscal_chave_acesso_and_more'),
        ('imoveis', '0022_alter_imovel_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixamovimento',
            options={'ordering': ['-data_hora'], 'permissions': [('lancar_movimento_caixa', 'Pode lançar movimento de caixa'), ('excluir_movimento_caixa', 'Pode excluir movimento de caixa')], 'verbose_name': 'Movimento de Caixa', 'verbose_name_plural': 'Movimentos de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='caixasessao',
            options={'ordering': ['-data', '-hora_abertura'], 'permissions': [('abrir_caixa', 'Pode abrir sessão de caixa'), ('fechar_caixa', 'Pode fechar sessão de caixa'), ('conferir_caixa', 'Pode conferir sessão de caixa')], 'verbose_name': 'Sessão de Caixa', 'verbose_name_plural': 'Sessões de Caixa'},
        ),
        migrations.AlterField(
            model_name='caixamovimento',
            name='banca_feira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to='imoveis.bancafeira'),
        ),
        migrations.AlterField(
            model_name='caixasessao',
            name='banca_feira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to='imoveis.bancafeira'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='chave_acesso',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, null=True, verbose_name='Chave de Acesso'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='numero_apolice',
            field=security.fields.EncryptedCharField(max_length=510, unique=True),
        ),
    ]
