# Generated by Django 5.1.5 on 2025-08-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('COMERCIAL', 'Comercial'), ('TERRENO', 'Terreno'), ('CHACARA', 'Chácara')], max_length=20)),
                ('finalidade', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('MISTO', 'Misto')], max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quartos', models.IntegerField(default=0)),
                ('banheiros', models.IntegerField(default=0)),
                ('vagas_garagem', models.IntegerField(default=0)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_condominio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_iptu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('mobiliado', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='imoveis/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Foto do Imóvel',
                'verbose_name_plural': 'Fotos dos Imóveis',
            },
        ),
    ]
