# Generated by Django 5.2.5 on 2025-10-02 18:11

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0014_layoutfeira_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='templatemapafeira',
            name='categoria',
            field=models.CharField(choices=[('TRADICIONAL', 'Feira Tradicional'), ('COBERTA', 'Feira Coberta'), ('SHOPPING_POPULAR', 'Shopping Popular'), ('ALIMENTACAO', 'Praça de Alimentação'), ('ARTESANATO', 'Feira de Artesanato'), ('PERSONALIZADO', 'Personalizado')], max_length=20, verbose_name='Categoria'),
        ),
    ]
