# Generated by Django 5.2.5 on 2025-10-03 17:25

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0015_remove_polo_moda'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratobancafeira',
            name='dias_vencimento_semanal',
            field=models.JSONField(blank=True, default=list, help_text='Lista com os dias da semana (0=Segunda, 1=Terça, 2=Quarta, 3=Quinta, 4=Sexta, 5=Sábado, 6=Domingo)', verbose_name='Dias da Semana para Vencimento'),
        ),
        migrations.AddField(
            model_name='contratobancafeira',
            name='tipo_vencimento',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMANAL', 'Semanal')], default='SEMANAL', max_length=10, verbose_name='Tipo de Vencimento'),
        ),
        migrations.AddField(
            model_name='contratobancafeira',
            name='valor_semanal',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Valor Semanal'),
        ),
        migrations.AlterField(
            model_name='contratobancafeira',
            name='dia_vencimento',
            field=models.IntegerField(default=10, verbose_name='Dia de Vencimento (para vencimento mensal)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
