# Generated by Django 5.2.5 on 2025-10-03 20:38

import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0016_contratobancafeira_dias_vencimento_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancafeira',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADA', 'Ocupada'), ('MANUTENCAO', 'Em Manutenção'), ('INDISPONIVEL', 'Indisponível'), ('JURIDICO', 'Jurídico')], default='DISPONIVEL', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
