# Generated by Django 5.2.5 on 2025-12-08 16:19

import security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0020_alter_imovel_inscricao_municipal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
