# Generated by Django 5.2.5 on 2026-03-10 16:55

import django.core.validators
import security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0023_layoutfeira_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaomapafeira',
            name='altura_mapa',
            field=models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Altura do Mapa (linhas)'),
        ),
        migrations.AlterField(
            model_name='configuracaomapafeira',
            name='largura_mapa',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Largura do Mapa (colunas)'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
