# Generated by Django 4.2.30 on 2026-05-04 13:41

from django.db import migrations
import security.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_documento_banca_remove_ticket_banca_and_more'),
        ('financeiro', '0022_alter_caixasessao_unique_together_and_more'),
        ('pagamentos', '0005_remove_pagamentobancafeira_contrato_banca_and_more'),
        ('notificacoes', '0003_notificacao_banca_feira_and_more'),
        ('imoveis', '0026_alter_bancafeira_posicao_coluna_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaomapafeira',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='configuracaomapafeira',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='contratobancafeira',
            name='banca_feira',
        ),
        migrations.RemoveField(
            model_name='contratobancafeira',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='contratobancafeira',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='fotobancafeira',
            name='banca',
        ),
        migrations.RemoveField(
            model_name='layoutfeira',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='layoutfeira',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='templatemapafeira',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
        migrations.DeleteModel(
            name='BancaFeira',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoMapaFeira',
        ),
        migrations.DeleteModel(
            name='ContratoBancaFeira',
        ),
        migrations.DeleteModel(
            name='FotoBancaFeira',
        ),
        migrations.DeleteModel(
            name='LayoutFeira',
        ),
        migrations.DeleteModel(
            name='TemplateMapaFeira',
        ),
    ]
