# Generated by Django 4.2.30 on 2026-05-04 13:56

from django.db import migrations
import security.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0027_alter_configuracaomapafeira_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_municipal',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=security.fields.EncryptedCharField(blank=True, max_length=510, verbose_name='Matrícula'),
        ),
    ]
