# Generated by Django 5.2.5 on 2025-09-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
    ]
