# Generated by Django 5.2.5 on 2025-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_auto_20250903_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoonline',
            name='categoria_pagamento',
            field=models.CharField(choices=[('INQUILINO', 'Pagamento de Inquilino (Aluguel)'), ('ASSINATURA', 'Pagamento de Assinatura (Plano)'), ('OUTROS', 'Outros')], default='INQUILINO', max_length=20, verbose_name='Categoria do Pagamento'),
        ),
    ]
