# Generated by Django 4.2.30 on 2026-05-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_pagamentobancafeira_logpagamentobanca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamentobancafeira',
            name='contrato_banca',
        ),
        migrations.DeleteModel(
            name='LogPagamentoBanca',
        ),
        migrations.DeleteModel(
            name='PagamentoBancaFeira',
        ),
    ]
