# Generated by Django 5.1.5 on 2025-09-22 17:45

import django.db.models.deletion
import django.utils.timezone
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_tenant'),
        ('core', '0009_alter_pessoa_agencia_alter_pessoa_banco_and_more'),
        ('documentos', '0001_initial'),
        ('imoveis', '0008_alter_imovel_inscricao_municipal_and_more'),
        ('saas', '0006_pagamentoplano_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal', max_length=7)),
                ('icone', models.CharField(default='bi-folder', help_text='Classe do ícone Bootstrap', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Documento',
                'verbose_name_plural': 'Categorias de Documentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_externo', models.EmailField(blank=True, help_text='Para compartilhamento com usuários externos', max_length=254)),
                ('tipo_acesso', models.CharField(choices=[('LEITURA', 'Somente Leitura'), ('DOWNLOAD', 'Leitura e Download'), ('EDICAO', 'Edição')], default='LEITURA', max_length=20)),
                ('token_acesso', models.CharField(blank=True, max_length=64, unique=True)),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('acessos', models.PositiveIntegerField(default=0)),
                ('limite_acessos', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compartilhamento',
                'verbose_name_plural': 'Compartilhamentos',
                'ordering': ['-data_compartilhamento'],
            },
        ),
        migrations.CreateModel(
            name='LogAcessoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('VISUALIZAR', 'Visualizar'), ('DOWNLOAD', 'Download'), ('EDITAR', 'Editar'), ('EXCLUIR', 'Excluir'), ('COMPARTILHAR', 'Compartilhar')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='confidencialidade',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('INTERNO', 'Interno'), ('CONFIDENCIAL', 'Confidencial'), ('RESTRITO', 'Restrito')], default='INTERNO', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_arquivamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_documento',
            field=models.DateField(blank=True, help_text='Data do documento original', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='hash_arquivo',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documento',
            name='nome_original',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=500),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ARQUIVADO', 'Arquivado'), ('VENCIDO', 'Vencido'), ('PENDENTE', 'Pendente Aprovação')], default='ATIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='tamanho_arquivo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_aprovacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='categoria',
            field=models.CharField(choices=[('CONTRATO', 'Contrato'), ('PESSOA', 'Pessoa'), ('IMOVEL', 'Imóvel'), ('FINANCEIRO', 'Financeiro'), ('JURIDICO', 'Jurídico'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='vistoria',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=documentos.models.upload_documento_path),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'tipo'], name='documentos__tenant__1beda4_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'status'], name='documentos__tenant__5cfa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['hash_arquivo'], name='documentos__hash_ar_91ec09_idx'),
        ),
        migrations.AddField(
            model_name='categoriadocumento',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='documentos.categoriadocumento'),
        ),
        migrations.AddField(
            model_name='categoriadocumento',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='compartilhamentodocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='compartilhamentodocumento',
            name='usuario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compartilhamentodocumento',
            name='usuario_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logacessodocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='logacessodocumento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
