# Generated by Django 5.2.5 on 2025-08-26 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('core', '0001_initial'),
        ('notificacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em hexadecimal', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Template',
                'verbose_name_plural': 'Categorias de Templates',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='tiponotificacao',
            options={'verbose_name': 'Tipo de Notificação (Legado)', 'verbose_name_plural': 'Tipos de Notificação (Legado)'},
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='anexos',
            field=models.JSONField(default=list, help_text='Lista de anexos'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='corpo_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_clique',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='data_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='ip_abertura',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='log_tentativas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tentativas_maximas',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tentativas_realizadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='assunto',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification')], default='EMAIL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('ABERTA', 'Aberta'), ('CLICADA', 'Clicada'), ('ERRO', 'Erro'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificacaoAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campanha', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('filtro_personalizado', models.JSONField(default=dict, help_text='Filtros para seleção automática')),
                ('data_envio', models.DateTimeField()),
                ('recorrencia', models.CharField(choices=[('UNICA', 'Única'), ('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='UNICA', max_length=20)),
                ('intervalo_recorrencia', models.PositiveIntegerField(default=1, help_text='Intervalo para recorrência')),
                ('data_fim_recorrencia', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('max_tentativas', models.PositiveIntegerField(default=3)),
                ('intervalo_tentativas', models.PositiveIntegerField(default=60, help_text='Minutos entre tentativas')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('PROCESSANDO', 'Processando'), ('ENVIADA', 'Enviada'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('tentativas_realizadas', models.PositiveIntegerField(default=0)),
                ('ultima_tentativa', models.DateTimeField(blank=True, null=True)),
                ('proximo_envio', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquilinos', models.ManyToManyField(blank=True, to='core.inquilino')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação Agendada',
                'verbose_name_plural': 'Notificações Agendadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacoes.notificacaoagendada'),
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('COBRANCA', 'Cobrança'), ('VENCIMENTO', 'Vencimento'), ('BOAS_VINDAS', 'Boas-vindas'), ('RENOVACAO', 'Renovação'), ('MANUTENCAO', 'Manutenção'), ('COMUNICADO', 'Comunicado'), ('LEMBRETE', 'Lembrete'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('assunto_template', models.CharField(help_text='Use {{variavel}} para campos dinâmicos', max_length=300)),
                ('corpo_template', models.TextField(help_text='Use {{variavel}} para campos dinâmicos')),
                ('formato', models.CharField(choices=[('HTML', 'HTML'), ('TEXTO', 'Texto Simples')], default='HTML', max_length=10)),
                ('variaveis_disponiveis', models.JSONField(default=dict, help_text='Variáveis disponíveis para este template')),
                ('preview_dados', models.JSONField(default=dict, help_text='Dados de exemplo para preview')),
                ('ativo', models.BooleanField(default=True)),
                ('padrao', models.BooleanField(default=False, help_text='Template padrão para este tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.categoriatemplate')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='notificacaoagendada',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacoes.templatenotificacao'),
        ),
        migrations.CreateModel(
            name='EstatisticaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=20)),
                ('data_referencia', models.DateField()),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push Notification')], max_length=20)),
                ('total_enviadas', models.PositiveIntegerField(default=0)),
                ('total_entregues', models.PositiveIntegerField(default=0)),
                ('total_abertas', models.PositiveIntegerField(default=0)),
                ('total_clicadas', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('total_rejeitadas', models.PositiveIntegerField(default=0)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_clique', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_erro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tempo_medio_abertura', models.DurationField(blank=True, null=True)),
                ('tempo_medio_clique', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacoes.templatenotificacao')),
            ],
            options={
                'verbose_name': 'Estatística de Notificação',
                'verbose_name_plural': 'Estatísticas de Notificações',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notificacoes.templatenotificacao'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['status', 'canal'], name='notificacoe_status_5d5905_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['inquilino', 'created_at'], name='notificacoe_inquili_118b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tracking_id'], name='notificacoe_trackin_d63613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatenotificacao',
            unique_together={('tipo', 'padrao')},
        ),
        migrations.AlterUniqueTogether(
            name='estatisticanotificacao',
            unique_together={('periodo', 'data_referencia', 'canal', 'template')},
        ),
    ]
