# Generated by Django 5.2.5 on 2025-09-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_alter_imovel_inscricao_municipal_and_more'),
        ('notificacoes', '0002_categoriatemplate_alter_tiponotificacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='banca_feira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.bancafeira', verbose_name='Banca de Feira'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='contrato_banca_feira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imoveis.contratobancafeira', verbose_name='Contrato de Banca de Feira'),
        ),
        migrations.AddField(
            model_name='notificacaoagendada',
            name='bancas_feira',
            field=models.ManyToManyField(blank=True, to='imoveis.bancafeira', verbose_name='Bancas de Feira'),
        ),
    ]
