# Generated by Django 5.1.5 on 2026-04-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_cobranca_automatica_log'),
        ('saas', '0007_evolutioninstance_evolutionmessage_evolutionwebhook'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name='WhatsAppMensagemConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo', models.CharField(choices=[('GERAL', 'Mensagem Geral'), ('COBRANCA_ALUGUEL', 'Cobrança Aluguel'), ('COBRANCA_IPTU', 'Cobrança IPTU')], max_length=30)),
                        ('mensagem', models.TextField(blank=True)),
                        ('anexo', models.FileField(blank=True, null=True, upload_to='notificacoes/whatsapp/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant')),
                    ],
                    options={
                        'verbose_name': 'Configuração WhatsApp',
                        'verbose_name_plural': 'Configurações WhatsApp',
                        'ordering': ['tipo'],
                        'unique_together': {('tenant', 'tipo')},
                    },
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='notificacao',
                    name='banca_feira',
                ),
                migrations.RemoveField(
                    model_name='notificacao',
                    name='contrato_banca_feira',
                ),
                migrations.RemoveField(
                    model_name='notificacaoagendada',
                    name='bancas_feira',
                ),
                migrations.CreateModel(
                    name='WhatsAppMensagemConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo', models.CharField(choices=[('GERAL', 'Mensagem Geral'), ('COBRANCA_ALUGUEL', 'Cobrança Aluguel'), ('COBRANCA_IPTU', 'Cobrança IPTU')], max_length=30)),
                        ('mensagem', models.TextField(blank=True)),
                        ('anexo', models.FileField(blank=True, null=True, upload_to='notificacoes/whatsapp/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.tenant')),
                    ],
                    options={
                        'verbose_name': 'Configuração WhatsApp',
                        'verbose_name_plural': 'Configurações WhatsApp',
                        'ordering': ['tipo'],
                        'unique_together': {('tenant', 'tipo')},
                    },
                ),
            ],
        ),
    ]
